export default
{
    apiAuthRegister: "/api/auth/register",
    apiAuthLogin: "/api/auth/login",
    apiAuthResetPassword: "/api/auth/reset-password",
    apiAuthValidateResetPasswordToken: "/api/auth/validate-reset-password-token",
    apiAuthChangePassword: "/api/auth/change-password",
    apiAuthChangeUserPassword: "/api/auth/change-user-password",
    apiAuthLogout: "/api/auth/logout",
    apiAuthCheck: "/api/auth/check",
    apiAuthRefreshAccessToken: "/api/auth/refresh-access-token",
    apiUserInfo: "/api/user/info",

    apiUserAdd: "/api/user/add",
    apiUserEdit: "/api/user/edit",
    apiUserGet: "/api/user/get",
    apiUserDetail: "/api/user/detail",
    apiUserDelete: "/api/user/delete",
    apiUserList: "/api/user/list",
    apiUserActive: "/api/user/active",
    apiUserPresent: "/api/user/present",

    apiMenuAdd: "/api/menu/add",
    apiMenuEdit: "/api/menu/edit",
    apiMenuGet: "/api/menu/get",
    apiMenuDetail: "/api/menu/detail",
    apiMenuDelete: "/api/menu/delete",
    apiMenuList: "/api/menu/list",
    apiMenuActive: "/api/menu/active",

    apiCustomerSupportRequestAdd: "/api/customer-support-request/add",
    apiCustomerSupportRequestEdit: "/api/customer-support-request/edit",
    apiCustomerSupportRequestGet: "/api/customer-support-request/get",
    apiCustomerSupportRequestDetail: "/api/customer-support-request/detail",
    apiCustomerSupportRequestDelete: "/api/customer-support-request/delete",
    apiCustomerSupportRequestList: "/api/customer-support-request/list",
    apiCustomerSupportRequestActive: "/api/customer-support-request/active",

    apiSettingAdd: "/api/setting/add",
    apiSettingEdit: "/api/setting/edit",
    apiSettingGet: "/api/setting/get",
    apiSettingDetail: "/api/setting/detail",
    apiSettingDelete: "/api/setting/delete",

    apiCertificateGet: "/api/certificate/get",
    apiCertificateAdd: "/api/certificate/add",
    apiCertificateEdit: "/api/certificate/edit",
    apiCertificateDetail: "/api/certificate/detail",
    apiCertificateDelete: "/api/certificate/delete",
    apiCertificateList: "/api/certificate/list",
    apiCertificateActive: "/api/certificate/active",

    apiProductGet: "/api/product/get",
    apiProductAdd: "/api/product/add",
    apiProductEdit: "/api/product/edit",
    apiProductDetail: "/api/product/detail",
    apiProductDelete: "/api/product/delete",
    apiProductList: "/api/product/list",
    apiProductActive: "/api/product/active",

    apiTestimonialGet: "/api/testimonial/get",
    apiTestimonialAdd: "/api/testimonial/add",
    apiTestimonialEdit: "/api/testimonial/edit",
    apiTestimonialDetail: "/api/testimonial/detail",
    apiTestimonialDelete: "/api/testimonial/delete",
    apiTestimonialList: "/api/testimonial/list",
    apiTestimonialActive: "/api/testimonial/active",

    apiBlogGet: "/api/blog/get",
    apiBlogAdd: "/api/blog/add",
    apiBlogEdit: "/api/blog/edit",
    apiBlogDetail: "/api/blog/detail",
    apiBlogDelete: "/api/blog/delete",
    apiBlogList: "/api/blog/list",
    apiBlogActive: "/api/blog/active",

    apiDynamicPageGet: "/api/dynamic-page/get",
    apiDynamicPageAdd: "/api/dynamic-page/add",
    apiDynamicPageEdit: "/api/dynamic-page/edit",
    apiDynamicPageDetail: "/api/dynamic-page/detail",
    apiDynamicPageDelete: "/api/dynamic-page/delete",
    apiDynamicPageList: "/api/dynamic-page/list",
    apiDynamicPageActive: "/api/dynamic-page/active",

    apiAttachmentDetail: "/api/attachment/detail",

    apiDashboardCustomerGet: "/api/dashboard/customer",
    apiDashboardAdminGet: "/api/dashboard/admin",

    apiLog: "/api/log"
}
